-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.persons
(
    id serial NOT NULL,
    first_name character varying(45) NOT NULL,
    last_name character varying(45) NOT NULL,
    nick_name character varying(45),
    birthdate date NOT NULL,
    is_female boolean,
    parent_id integer,
    user_id integer,
    goal_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public."user"
(
    id serial NOT NULL,
    user_name character varying(45) NOT NULL,
    password character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.relations
(
    child_id serial NOT NULL,
    child_parent_id integer NOT NULL,
    "is_Custodial" boolean NOT NULL,
    "is_Blocked" boolean NOT NULL,
    PRIMARY KEY (child_id)
);

CREATE TABLE public.teams
(
    id serial NOT NULL,
    name character varying(45) NOT NULL,
    age integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.game
(
    game_id serial NOT NULL,
    home_team_id integer NOT NULL,
    away_team_id integer NOT NULL,
    game_time daterange,
    surface_id integer,
    field_number integer,
    PRIMARY KEY (home_team_id)
);

CREATE TABLE public.team_members
(
    id serial NOT NULL,
    team_id integer NOT NULL,
    member_id integer NOT NULL,
    role character varying(45) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.game_team
(
    game_id integer NOT NULL,
    team_id integer NOT NULL,
    is_home boolean NOT NULL,
    PRIMARY KEY (game_id, team_id)
);

CREATE TABLE public.person_person_link
(
    person1_id integer NOT NULL,
    person2_id integer NOT NULL,
    person1_role character varying NOT NULL,
    person2_role character varying NOT NULL,
    PRIMARY KEY (person1_id, person2_id)
);

CREATE TABLE public.goals
(
    id serial NOT NULL,
    title character varying NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.relations
    ADD FOREIGN KEY (child_parent_id)
    REFERENCES public.persons (id)
    NOT VALID;


ALTER TABLE public.team_members
    ADD FOREIGN KEY (team_id)
    REFERENCES public.teams (id)
    NOT VALID;


ALTER TABLE public.team_members
    ADD FOREIGN KEY (member_id)
    REFERENCES public.persons (id)
    NOT VALID;


ALTER TABLE public.game_team
    ADD FOREIGN KEY (game_id)
    REFERENCES public.game (game_id)
    NOT VALID;


ALTER TABLE public.game_team
    ADD FOREIGN KEY (team_id)
    REFERENCES public.teams (id)
    NOT VALID;


ALTER TABLE public.person_person_link
    ADD FOREIGN KEY (person1_id)
    REFERENCES public.persons (id)
    NOT VALID;


ALTER TABLE public.person_person_link
    ADD FOREIGN KEY (person2_id)
    REFERENCES public.persons (id)
    NOT VALID;


ALTER TABLE public.goals
    ADD FOREIGN KEY (id)
    REFERENCES public.persons (goal_id)
    NOT VALID;


ALTER TABLE public.persons
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id)
    NOT VALID;

END;